### ISSUE TITLE
TypeErroe in StateDecorator in tests

### ISSUE THREAD

**Issue by eszthoff** [Sambego/storybook-state#34]
After updating to 2.0.1, we get a jest failure with the following error: 
```
TypeError: (0 , _addons.makeDecorator) is not a function
at Object.<anonymous> (node_modules/@sambego/storybook-state/dist/StateDecorator.js:17:45)
      at Object.<anonymous> (node_modules/@sambego/storybook-state/dist/index.js:14:23)
```

__Expected behaviour:__
No errors upon import.

**Comment by eszthoff** [comment]
Sorry, it was a problem with some mock we had.
